name: build
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          description: deploy to production
      - run: |
          echo deploy here...
      - uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'
        
      
      
