name: build
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo deploy here...
        
      
      
